### ISSUE TITLE
Doesn't work in Neovim

### ISSUE THREAD

**Issue by ranelpadon** [obcat/vim-hitspop#12]
Just noticed that it works in my Vim and MacVim, but not in Neovim, is that expected? Or do I need to tweak some settings. Or does Neovim has different Popup API? Thanks :)

**Comment by obcat** [comment]
Thanks for using my plugin!

> Just noticed that it works in my Vim and MacVim, but not in Neovim, is that expected?

Unfortunately, yes. This plugin does not support Neovim. This is because I'm not a Neovim user.

> Or do I need to tweak some settings. Or does Neovim has different Popup API?

This plugin cannot be used just tweaking settings in Neovim. As you say, Neovim has different Popup API from Vim, so supporting Neovim needs a lot of work on the source code. Also, even if a PR to support Neovim is send, I am not going to merge it, since I can't maintain the code.

I'll add a note to the README that this plugin cannot be used in Neovim.

Thanks.

**Comment by ranelpadon** [comment]
@obcat Ah ok, thanks for the clarifications, just wanna make sure that I'm not missing something! Please close this issue once you update the README. :)

**Comment by obcat** [comment]
Thanks:) I've updated, so closing. Have a nice day!
